### ISSUE TITLE
Crash on Android device

### ISSUE THREAD

**Issue by ljudbane** [alan-ai/alan-sdk-ionic#24]
Sometimes when running project on Android device, the app will crash as soon as Alan button is initialized. It doesn't happen regularly - on the same device it will sometimes work and sometimes crash. This behaviour was observed when running ionic debug build from Android studio to physical Android device (NOKIA 8 TA-1004, running Android 9).

When crash happens, we have observed 2 different errors in Android Studio's run log.

1. Exception with stack trace:
E/AndroidRuntime: FATAL EXCEPTION: Thread-10
    Process: xx.app, PID: 26930
    java.lang.IllegalThreadStateException
        at java.lang.Thread.start(Thread.java:724)
        at com.alan.alansdk.alanbase.recorder.AlanRecorder.startRecording(AlanRecorder.java:30)
        at com.alan.alansdk.Alan.record(Alan.java:143)
        at com.alan.alansdk.Alan.onDialogStateChanged(Alan.java:408)

[crash1-edit.txt](https://github.com/alan-ai/alan-sdk-ionic/files/7642312/crash1-edit.txt)

2. Single error message (not sure if it's the cause of crash, but it's not present in log when it doesn't crash):
E/AudioRecord: start() status -38

[crash2-edit.txt](https://github.com/alan-ai/alan-sdk-ionic/files/7642329/crash2-edit.txt)

If there's any other information we can provide that will help you locate the problem, please tell us.

**Comment by snyuryev** [comment]
Hey @ljudbane 
Do you have crash on different device or emulator?
Could you provide source code with minimal example of the app and studio script?

**Comment by ljudbane** [comment]
@snyuryev This only happened on one specific device (Nokia 8). We have tested on some other Android devices but could not reproduce the issue.
